export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const MAKE_BUSINESS = 'MAKE_BUSINESS';
export const MAKE_PERSONAL = 'MAKE_PERSONAL';
export const NEXT_STEP = 'NEXT_STEP';
export const PREV_STEP = 'PREV_STEP';
export const VALIDATE_FIELD = 'VALIDATE_FIELD';